CREATE DATABASE PokeBattle;
USE PokeBattle;

CREATE TABLE IF NOT EXISTS POKEMON (
	`POKE_ID` INT  NOT NULL AUTO_INCREMENT,
	`POKE_PSEUDO` VARCHAR(255),
	`POKE_NAME` VARCHAR(255),
	`POKE_LEVEL` INT DEFAULT 1,
	`POKE_PV` INT DEFAULT 0,
	PRIMARY KEY(`POKE_ID`)
);